name: smart_attendance_mobile_app
description: "The primary client-side application for the Smart Attendance System."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  go_router: ^14.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0

  # Firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Maps
  google_maps_flutter: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/