name: Deploy to Staging
on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Artifacts
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Decode Android Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Build Android App Bundle
        run: flutter build appbundle --release
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Build iOS IPA
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-ipa
          path: build/ios/ipa/*.ipa

  deploy-firebase-staging:
    name: Deploy Firebase to Staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}'

      - name: Deploy Firebase Assets
        run: firebase deploy --only functions,firestore,storage,hosting --project <your-staging-project-id> --non-interactive

  deploy-android-staging:
    name: Deploy Android to Staging
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-release-bundle

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}
          packageName: com.smart.attendance.app
          releaseFiles: app-release.aab
          track: internal

  deploy-ios-staging:
    name: Deploy iOS to Staging
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download iOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-release-ipa

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v2
        with:
          api-key-json: ${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}
          app-bundle-id: com.smart.attendance.app.ios
          ipa-path: ./*.ipa